---
title: "Publications"
output:
  blogdown::html_page:
    keep_md: yes
date: "`r Sys.Date()`"
toc: true
---

## Preprints

```{r preprint, echo=FALSE, results='asis'}
preprint_refs <- RefManageR::ReadBib("preprintList.bib")
print(preprint_refs, .opts = list(style = "html", bib.style = "authoryear", first.inits = TRUE,
                                  no.print.fields = c("ISSN", "urldate", "language", "url", "editor", "note"), sorting = "ydnt",
                                  dashed = FALSE))
```

## Publications

```{r pubsRead, echo=FALSE, results='asis'}
pubs_refs <- RefManageR::ReadBib("publicationList.bib")
```

### *2025*
```{r pubs2025, echo=FALSE, results='asis'}
print(pubs_refs[year = "2025"], .opts = list(style = "html", bib.style = "authoryear", first.inits = TRUE,
                                             no.print.fields = c("ISSN", "urldate", "language", "url", "editor", "note"),
                                             sorting = "ydnt",
                                             dashed = FALSE))
```

### *2023*
```{r pubs2023, echo=FALSE, results='asis'}
print(pubs_refs[year = "2023"], .opts = list(style = "html", bib.style = "authoryear", first.inits = TRUE,
                                             no.print.fields = c("ISSN", "urldate", "language", "url", "editor", "note"),
                                             sorting = "ydnt",
                                             dashed = FALSE))
```

### *2022*
```{r pubs2022, echo=FALSE, results='asis'}
print(pubs_refs[year = "2022"], .opts = list(style = "html", bib.style = "authoryear", first.inits = TRUE,
                                             no.print.fields = c("ISSN", "urldate", "language", "url", "editor", "note"),
                                             sorting = "ydnt",
                                             dashed = FALSE))
```

### *2021*
```{r pubs2021, echo=FALSE, results='asis'}
print(pubs_refs[year = "2021"], .opts = list(style = "html", bib.style = "authoryear", first.inits = TRUE,
                                             no.print.fields = c("ISSN", "urldate", "language", "url", "editor", "note"),
                                             sorting = "ydnt",
                                             dashed = FALSE))
```

### *2020*
```{r pubs2020, echo=FALSE, results='asis'}
print(pubs_refs[year = "2020"], .opts = list(style = "html", bib.style = "authoryear", first.inits = TRUE,
                                             no.print.fields = c("ISSN", "urldate", "language", "url", "editor", "note"),
                                             sorting = "ydnt",
                                             dashed = FALSE))
```

### *2019*
```{r pubs2019, echo=FALSE, results='asis'}
print(pubs_refs[year = "2019"], .opts = list(style = "html", bib.style = "authoryear", first.inits = TRUE,
                                             no.print.fields = c("ISSN", "urldate", "language", "url", "editor", "note"),
                                             sorting = "ydnt",
                                             dashed = FALSE))
```

### *2018*
```{r pubs2018, echo=FALSE, results='asis'}
print(pubs_refs[year = "2018"], .opts = list(style = "html", bib.style = "authoryear", first.inits = TRUE,
                                             no.print.fields = c("ISSN", "urldate", "language", "url", "editor", "note"),
                                             sorting = "ydnt",
                                             dashed = FALSE))
```

## Alternative Lists of Publications

<a href="https://orcid.org/0000-0001-9554-0605">> Orcid | orcid.org/0000-0001-9554-0605</a>

<a href="https://www.researchgate.net/profile/Benjamin_Marshall5">> ResearchGate | www.researchgate.net/profile/Benjamin_Marshall5</a>

<a href="https://scholar.google.com/citations?user=K15GGjkAAAAJ&hl=en">> Google Scholar | scholar.google.com/citations?user=K15GGjkAAAAJ</a>